Fixed a bug with redefinition of symbols in REPL. Exported missing bitwise-bit-field procedure. Fixed a brace bug in bitwise-rotate-bit-field.
git-tfs-id: [https://tfs.codeplex.com:443/tfs/TFS02]$/IronScheme;C18362